---
apiVersion: v1
kind: Namespace
metadata:
  name: gravity
  labels:
    app: gravity-pms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gravity-config
  namespace: gravity
data:
  NODE_ENV: "production"
  PORT: "3001"
  DB_HOST: "gravity-postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "gravity_db"
  REDIS_HOST: "gravity-redis-svc"
  REDIS_PORT: "6379"
  SWAGGER_ENABLED: "false"
  FRONTEND_URL: "https://app.gravity.io"
